"""Add updated_at and relationships

Revision ID: d3a249acbf1e
Revises: 0e7d1b2bc5e2
Create Date: 2025-04-04 21:37:52.179272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a249acbf1e'
down_revision: Union[str, None] = '0e7d1b2bc5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'updated_at')
    # ### end Alembic commands ###
